### ISSUE TITLE
Allow to add a hash to the downloaded manifest

### ISSUE THREAD

**Issue by Ekleog** [mozilla/nixpkgs-mozilla#113]
This would both make builds reproducible (without the current assumption that manifests are immutable), and much faster (because nix's pinning would work). And this would allow offline entering a nix-shell based on it.

Likely should be kept optional, for ease-of-use.

Current implementation idea: add a `sha256` parameter to `fromManifest` and `rustChannelOf`, and make `fromManifest` pass it through to `builtins.fetchurl`.

Sorry for not taking the time to do a PR for this (yet), hopefully I'll get to it someday, but feel free to do this if you have time :)

**Comment by nbp** [comment]
An other option would be to provide the manifest file as argument.

**Comment by nbp** [comment]
Fixed by #188
