### ISSUE TITLE
Cannot make Firefox Nightly default browser

### ISSUE THREAD

**Issue by asymmetric** [mozilla/nixpkgs-mozilla#125]
When I try changing any setting in the `Preferences` tab, the setting doesn't actually get saved and I see the following error in `journalctl`:

```
GConf Error: Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)
```

### Reproduce

* NixOS 18.09
* i3
* `nix-env -iA nixos.latest.firefox-nightly-bin -f <nixpkgs>`
* change a setting
* `journalctl -xe`

**Comment by nbp** [comment]
I do not know how to change that. Also, as far as I know, the preferences tab should be saved in your profile. Therefore I am a bit surprised that it does not save anything unless you have no write access to your home directory.

I am using the AwesomeWM and I did not noticed this issue.

**Comment by rail** [comment]
Do you still have this issue? I use the almost the same configuration (18.09+i3+firefox-nightly-bin), expect that I use `configuration.nix` to install things. I haven't seen any issues with the settings so far. Maybe the error is just a red herring... I'd check the permissions of the profile directory (`~/.mozilla/firefox`)  and maybe strace firefox.

**Comment by asymmetric** [comment]
Yes, I still have this issue. The occurrence of the DBus bug is too synchronous with my attempt at saving Firefox settings to be a red herring.

Could it have something to do with DBus not being started correctly?

The actual error is `GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files` - any clues in which `.service` that name is provided on your systems?

**Comment by rail** [comment]
> @rail do you also have `gnome-session` running?

I used to run `gnome-settings-daemon` explicitly from `~/.config/i3/config` in the past, but not anymore for at least 2-3 months. But I have a lot of gnome stuff [installed](https://github.com/rail/nixos-configs/blob/3e3f864e343f3efbee375d5aabf5cc0cdfab678b/modules/desktop.nix#L67). 

> any clues in which `.service` that name is provided on your systems?

I guess this one:
```
$ cat /nix/store/l26y2lfvwqnngrb48h9069ffgxzvh4l5-gconf-3.2.6/share/dbus-1/services/org.gnome.GConf.service                                                                                                                      
[D-BUS Service]
Name=org.gnome.GConf
Exec=/nix/store/l26y2lfvwqnngrb48h9069ffgxzvh4l5-gconf-3.2.6/libexec/gconfd-2
```

**Comment by asymmetric** [comment]
I realized this only happens when I'm trying to save Nightly as the default browser, not when setting Firefox-specific options. It makes sense, because in this case, Firefox is trying to talk to DBus to configure the option.

@rail could you try launching from CLI and setting nightly as the default?

**Comment by rail** [comment]
Yup, the same here. When I try to click on ["Make default"](https://img.lgtm.ca/dd4a193e.png) in the preferences tab I get this:
```
Jan 02 19:52:17 rhyme xsession[1292]: GConf Error: Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)
```

Do you think this should be displayed in the UI? I'd file an upstream bug in this case.

**Comment by asymmetric** [comment]
@rail I don't know if this should be displayed, but what I can say is that it's already relatively clear that it's not the default browser cause the text "Nightly is not your default browser" doesn't go away.

Do you think this is a problem in Firefox, or in the nix package?

It seems that Firefox is expectig GConf to be installed, and from what I can tell, GConf has been deprecated in favor of GSettings and dconf. This happens in the upstream nix package as well.

**Comment by asymmetric** [comment]
@rail If you could file the bug, I would be eternally grateful, I find bugzilla intimidating :)

**Comment by asymmetric** [comment]
Btw, firefox is compiled [without GConf](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/common.nix#L196), so not sure why it's still expecting it there.

**Comment by rail** [comment]
Sure, I can file a bug.

**Comment by rail** [comment]
> Btw, firefox is compiled [without GConf](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/common.nix#L196), so not sure why it's still expecting it there.

This is applicable for the derivations built from source, not the `latest.*` ones. They are vanilla binary builds, downloaded from mozilla.org.

**Comment by asymmetric** [comment]
I guess that’s the problem then?

**Comment by rail** [comment]
Yeah, this is why the bug report should go upstream. Still to be filed. :)

**Comment by asymmetric** [comment]
Shouldn’t we instead build without GConf?

Firefox provides the flag, we just have to use it; so I’d say the bug is rather on our end.

**Comment by rail** [comment]
I thought you pointed to the snippet where we do disable gconf when build from source. This repo doesn't use it (it uses the upstream binaries), thus we have different behaviour.

**Comment by rail** [comment]
We can't do it this repo, because the idea is to use the vanilla binaries without any modifications. Just wrapping with all required libs, so we can run the bit-to-bit version (no patchelf).

**Comment by rail** [comment]
Sorry for the delay, but I finally filed https://bugzilla.mozilla.org/show_bug.cgi?id=1520990

**Comment by asymmetric** [comment]
> We can't do it this repo, because the idea is to use the vanilla binaries without any modifications. Just wrapping with all required libs, so we can run the bit-to-bit version (no patchelf).

The root cause is unfixable then, closing this.
