### ISSUE TITLE
How to use in configuration.nix?

### ISSUE THREAD

**Issue by arximboldi** [mozilla/nixpkgs-mozilla#133]
I like to keep all my Nix stuff in configuration.nix (including pinning third-party github .nix stuff) so I can easily replicate the configuration everywhere and have all packages up and running.

However, I haven't found a way to use the "overlay" directly from configuration.nix.

I have tried something like:
```nix
let
  mozillaSrc = (import <nixpkgs> {}).fetchFromGitHub {
    owner  = "mozilla";
    repo   = "nixpkgs-mozilla";
    rev    = "0d64cf67dfac2ec74b2951a4ba0141bc3e5513e8";
    sha256 = "0ngj2rk898rq73rq2rkwjax9p34mjlh3arj8w9npwwd6ljncarmh";
  };
in {
   # ...
   nixpkgs.overlays = [ (import mozillaSrc) ];
   # ...
}
```

But the names exposed by the overlay (like `firefox-nightly-bin`) seem to be unavailable in the configuration, nor with `nix-env -iA nixos.firefox-nightly-bin` (even though I also would prefer to avoid `nix-env`).

I have also tried:
```nix
let
  mozillaSrc = (import <nixpkgs> {}).fetchFromGitHub {
    owner  = "mozilla";
    repo   = "nixpkgs-mozilla";
    rev    = "0d64cf67dfac2ec74b2951a4ba0141bc3e5513e8";
    sha256 = "0ngj2rk898rq73rq2rkwjax9p34mjlh3arj8w9npwwd6ljncarmh";
  };
  mozilla = import mozillaSrc;
in {
  environment.systemPackages = [ 
    # ... 
    mozilla.firefox-nightly-bin 
    # ... 
  ];
}
```
But then it complains about `firefox-nightly-bin` being a function.

Is what I want to do even possible? Any tricks I am missing?

Thanks!

**Comment by garbas** [comment]
Use `latest.firefox-nightly-bin`

and please reopen if this doesn't fixes your problem
