### ISSUE TITLE
Rustc sigsev after 08.01.2019

### ISSUE THREAD

**Issue by bkchr** [mozilla/nixpkgs-mozilla#151]
Hey, does anyone sees the following message:
```error: process didn't exit successfully: `rustc -vV` (signal: 11, SIGSEGV: invalid memory reference)```

For any rust nightly after `08.01.2019`?

**Comment by bbigras** [comment]
Yes see https://github.com/rust-lang/rust/issues/57518

**Comment by bkchr** [comment]
@bbigras ahh ty. I did not found this issue while searching for it.
