### ISSUE TITLE
Current rustc nightlies fail to run

### ISSUE THREAD

**Issue by nagisa** [mozilla/nixpkgs-mozilla#152]
[This line](https://github.com/mozilla/nixpkgs-mozilla/blob/d5e7929a643f8fbf1b20a0b844a9f941874cfb82/rust-overlay.nix#L165) adds a dependency on the c++ shared library, however recently rustc has been changed to link to libc++ statically. This means that with two instances of c++ loaded into the same address space the program crashes (this is an inherent limitation of the libc++).

For the newer rustc versions the `libc++` should not be elfpatched in.

See https://github.com/rust-lang/rust/issues/57518.

**Comment by nagisa** [comment]
I have verified that removing the line works, however it would be nice to keep the support for older dated nightlies/stable versions as well, so something smarter may need to be done.

cc @nbp

**Comment by nbp** [comment]
@nagisa is this true for stable as well, or should we remove this line based on a version check?

**Comment by nagisa** [comment]
FWIW rustc itself no longer links to llvm directly for quite a while, so if LLVM was working before, it will not stop working.

I verified that with the line in question removed stable versions 1.32, 1.28, 1.20 & 1.19 all appear to work fine (i.e. `echo "fn main() {}" | rustc - --emit=llvm-ir` produces reasonable results). 1.18 does no longer install because there are no `.xz` artefacts for versions below 1.19.
