### ISSUE TITLE
Couldn't resolve host name 'target.tar.bz2'

### ISSUE THREAD

**Issue by attente** [mozilla/nixpkgs-mozilla#169]
The overlay suddenly broke (was working quite well for me before):

```warning: unable to download 'target.tar.bz2/firefox-68.0a1.en-US.linux-x86_64.checksums': Couldn't resolve host name (6); retrying in 301 ms
warning: unable to download 'target.tar.bz2/firefox-68.0a1.en-US.linux-x86_64.checksums': Couldn't resolve host name (6); retrying in 667 ms
warning: unable to download 'target.tar.bz2/firefox-68.0a1.en-US.linux-x86_64.checksums': Couldn't resolve host name (6); retrying in 1202 ms
warning: unable to download 'target.tar.bz2/firefox-68.0a1.en-US.linux-x86_64.checksums': Couldn't resolve host name (6); retrying in 2442 ms
error: unable to download 'target.tar.bz2/firefox-68.0a1.en-US.linux-x86_64.checksums': Couldn't resolve host name (6)
```

It seems to suggest that it thinks the host name is `target.tar.bz2`.

**Comment by rail** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1539067, waiting on it

**Comment by glasserc** [comment]
I have a different error message for the same cause:

`error: value is null while a list was expected, at /nix/store/f4n3b2qh1zwjkhfh4z527q6zfskyczjb-nixpkgs-mozilla/firefox-overlay.nix:80:18
(use '--show-trace' to show detailed location information)`

**Comment by rail** [comment]
> I have a different error message for the same cause:
> 
> `error: value is null while a list was expected, at /nix/store/f4n3b2qh1zwjkhfh4z527q6zfskyczjb-nixpkgs-mozilla/firefox-overlay.nix:80:18 (use '--show-trace' to show detailed location information)`

This is probably something different, that line refers to checksums file parsing.

**Comment by attente** [comment]
In case this is blocking anyone from doing an upgrade, I ended up doing this:

```
diff --git a/home.nix b/home.nix
index 5ec6ac8..d613703 100644
--- a/home.nix
+++ b/home.nix
@@ -13,7 +13,12 @@ let mozilla = import (builtins.fetchGit {
     mozilla
     (self: super: {
       latest = {
-        firefox-nightly-bin = super.latest.firefox-nightly-bin;
+        firefox-nightly-bin = super.lib.firefoxOverlay.firefoxVersion {
+          name = "Firefox Nightly";
+          version = "68.0a1";
+          release = false;
+          timestamp = "2019-04-01-21-56-51";
+        };
 
         rustChannels.nightly.rust = super.latest.rustChannels.nightly.rust.override {
           targets = [
```

**Comment by rail** [comment]
The upstream bug has been resolved and I got an update today. \o/
