### ISSUE TITLE
llvm-tools-preview fails on nightly

### ISSUE THREAD

**Issue by abbec** [mozilla/nixpkgs-mozilla#181]
Having `llvm-tools-preview` in the list of `extensions` gives the following error when starting a `nix-shell`:

```
install: error: unable to find installation components
builder for '/nix/store/g9jivbci7kjl2kd0zcj0xia9qmrsgjhi-llvm-tools-preview.drv' failed with exit code 1
cannot build derivation '/nix/store/lp221kbz1bi7dmjfd9jcwq96a1m1lss9-rust-1.37.0-nightly-2019-06-23-de7c4e423.drv': 1 dependencies couldn't be built
```

**Comment by ejpcmac** [comment]
This now fails on 1.37.0 stable.

**Comment by kierdavis** [comment]
`rust-overlay.nix` contains a line
```bash
sed -i "s/llvm-tools-preview//" components
```
which effectively blacklists llvm-tools-preview, even if you include it in `extensions`.

By simply removing this line I was able to build https://github.com/rust-osdev/bootloader (which requires llvm-tools-preview) successfully.

Presumably this line exists for a reason, but commentary about why it is present and the option to not blacklist `llvm-tools-preview` would be useful to have.

**Comment by glasserc** [comment]
This was blacklisted in https://github.com/mozilla/nixpkgs-mozilla/pull/136. Based on the PR description, I am guessing that it was a temporary failure and that we can take it out, especially if you have used it successfully.

**Comment by kierdavis** [comment]
Created #206 to remove this line.
