### ISSUE TITLE
rust-overlay: rust-src fails on latest nightly

### ISSUE THREAD

**Issue by dnaq** [mozilla/nixpkgs-mozilla#183]
The following simplified nixos configuration:
```
environment.systemPackages = [
  let rust = latest.rustChannels.nightly.rust.override {
    extensions = [ "rust-src" ];
  };
  in rust
  ]
```

yields this error, since approximately yesterday:
```
building '/nix/store/7w6pfmmkirm0rhww6qimzvy0nmf0j06z-rust-src.drv'...
unpacking sources
unpacking source archive /nix/store/ma4hv9dgf0kd4ahbcc6ikm7jrzb1j0rw-rust-src-nightly.tar.xz
source root is rust-src-nightly
setting SOURCE_DATE_EPOCH to timestamp 1561817711 of file rust-src-nightly/rust-src/manifest.in
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
patching script interpreter paths in install.sh
/nix/store/mmy628bwa67s49afik1pm4niab56h280-stdenv-linux/setup: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory
builder for '/nix/store/7w6pfmmkirm0rhww6qimzvy0nmf0j06z-rust-src.drv' failed with exit code 126
cannot build derivation '/nix/store/rphq41zxgagbii159khfcmsnsljf08hr-rust-1.37.0-nightly-2019-06-29-9a90d03ad.drv': 1 dependencies couldn't be built
```

**Comment by nbp** [comment]
For reference, here is the failing line: https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix#L149 .
This would be an issue to address either as part of the generation of the `install.sh` script provided and/or as part of the `patchShebang` function [provided by Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/patch-shebangs.sh)

**Comment by arcnmx** [comment]
This seems like an [upstream issue](https://github.com/rust-lang/rust-installer/issues/95) though not sure where or why, probably it's suddenly running on windows now? There's probably no reason to work around it in the overlay, it's not like this is working anywhere else either. Unfortunately rustup presumably doesn't use that script, so the breakage isn't obvious to most nightly users...

**Comment by dnaq** [comment]
We can work around this issue by adding:
``
${self.dos2unix}/bin/dos2unix install.sh
``

At the beginning of installPhase, line 148, in the overlay.

**Comment by nbp** [comment]
This seems to have been fixed upstream: https://github.com/rust-lang/rust/issues/62276
