### ISSUE TITLE
firefox-nightly: alias'ed binary name?

### ISSUE THREAD

**Issue by colemickens** [mozilla/nixpkgs-mozilla#189]
Hi.

I've been using Nightly for a very long time now, but it is just not sustainable anymore. I am regularly finding myself using Chromium because Nightly just regresses frequently under Linux, particularly Wayland.

But... I have reported at least a couple bugs and like to be a guinea pig, so I'd like to keep them installed side-by-side. However, I'm not really sure how to do this without having conflicts for `firefox`.

Is it possible to utilize `latest.firefox` while having the binary be named `firefox-nightly`?

**Comment by colemickens** [comment]
I was able to figure this out with some help from folks in #nixos.

Here's some inspiration for someone else. Basically, use `writeShellScriptBin` to wrap the binary with another name: https://github.com/colemickens/nixcfg/commit/d9f5595526d9a64ea3afe0bf3d6defff5c55bb58

**Comment by nbp** [comment]
@colemickens Thanks for opening this issue and providing a work-around. Sorry for not answering back in due time.

If you still find issue while using firefox nightly, feel free to open a bug on https://bugzilla.mozilla.org/ , if you have not done so already.
