### ISSUE TITLE
build latest Firefox using ALSA

### ISSUE THREAD

**Issue by krackout** [mozilla/nixpkgs-mozilla#216]
Starting from 70.0.1 I think, I have no sound from Firefox. I use nix package manager on a Debian Linux alsa only system.
Since alsa is not completely dropped from Firefox, how can I build/install firefox from nix package manager?
My apologies if this is not the proper place to ask; in such case guide me if you like to where to address such a question. Thank you.

**Comment by glasserc** [comment]
How did you install Firefox normally?

I'm not a Nix expert, but if you installed it by putting a `firefox` derivation somewhere, maybe you can try `firefox.override { MOZ_ALSA = true; }`.

**Comment by krackout** [comment]
my Firefox Nix installation was done typing:

nix-env -i firefox

I also tried to remove it, garbage collected to be fully removed and re-installed, same command.

I'll search for how to make an override on non-NixOS. If you have any idea please advice.

**Comment by glasserc** [comment]
Sorry, I'm not sure myself. Where I would start is by creating `~/.config/nixpkgs/overlays/firefox-alsa-overlay.nix` with contents like this:

```
self: super:

{
  firefox = super.firefox.override { MOZ_ALSA = true };
}
```

But I have no idea whether this will work or what to try if it doesn't. You might try asking in one of the community resources listed at https://nixos.org/nixos/community.html, they should be able to help with setting up an overlay that sets the environment variables correctly.

**Comment by krackout** [comment]
```
self: super: {
  firefox = self.wrapFirefox (super.firefox-unwrapped.override
    { pulseaudioSupport = false;
      alsaSupport = true;
    });
}

```

Got help from Nix IRC channel, the above overlay is syntax correct, no errors. Removed-reinstalled firefox, yet still no sound!

**Comment by glasserc** [comment]
Unfortunately, this is beyond my level of expertise. The derivation for Firefox that actually does the build isn't even in this repository -- it's at https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/common.nix#L238. It looks like it just passes an `--enable-alsa` flag to the configure script. I imagine that if there were an obvious way to get it to work, that would be it. I do know that there was some heated discussion about [Mozilla no longer supporting ALSA](https://groups.google.com/d/msg/mozilla.dev.platform/jRAqSTri66I/wrWZJIiEDAAJ) a couple years ago... maybe there's just a bug in the ALSA support? Sorry, I really don't know where to go with this.

**Comment by krackout** [comment]
Nevermind, I'll leave with Firefox ESR in case I don't find a solution for Firefox current. Thank you very much!
