### ISSUE TITLE
Add custom Rust targets

### ISSUE THREAD

**Issue by piegamesde** [mozilla/nixpkgs-mozilla#265]
I don't really know how this overlay works in detail, but I'd like to be able to add new custom targets that are not provided by Rust. I already have some .json file but I don't know how to integrate it.

**Comment by nbp** [comment]
If the target is not part of the manifest file, this would be difficult.
Can you describe or paste a version of the json file? Is it supposed to replace the manifest file which is currently used?

**Comment by piegamesde** [comment]
My target file:

```json
{
  "arch": "riscv32",
  "atomic-cas": false,
  "cpu": "generic-rv32",
  "data-layout": "e-m:e-p:32:32-i64:64-n32-S128",
  "eh-frame-header": false,
  "emit-debug-gdb-scripts": false,
  "executables": true,
  "features": "+m",
  "is-builtin": false,
  "linker": "rust-lld",
  "linker-flavor": "ld.lld",
  "llvm-target": "riscv32",
  "max-atomic-width": 0,
  "panic-strategy": "abort",
  "relocation-model": "static",
  "target-pointer-width": "32"
}
```

See also https://rustc-dev-guide.rust-lang.org/building/new-target.html and https://doc.rust-lang.org/rustc/targets/custom.html

**Comment by nbp** [comment]
This overlay works by using the manifest.toml file used by rustup, to provide pre-built version listed in the manifest file. Then they are patched to make these pre-built binary work on NixOS systems.

I am not familiar with adding new targets for Rust. These JSON files seems to be used to compile a custom version of Rust which is not pre-built, as I understand it.

Unfortunately, this overlay only provide existing versions. Looking at the `manifest.toml` file which is provided in `<output>/nix-support/manifest.json`, we can find the following targets, as pre-compiled available targets:
```
riscv32i-unknown-none-elf
riscv32imc-unknown-none-elf
riscv32imac-unknown-none-elf
riscv32gc-unknown-linux-gnu
```

If this overlay were to compile Rust from sources, then I guess this could be used, to make a custom version of Rust for a given target, but this is not the case.

I know this is not the answer you are looking for, but I have no better answer to give you right now :/

**Comment by piegamesde** [comment]
I understand. Although custom Rust targets do not necessarily mean a recompilation of rustc (in my case, only `std` has to be compiled), this probably won't work nevertheless.
