### ISSUE TITLE
rust-overlay - Install other std targets

### ISSUE THREAD

**Issue by Havvy** [mozilla/nixpkgs-mozilla#27]
Currently the overlay only installs the `rust-std` for the target you are building on/(for?). Should either download all targets by default or let us pass in a parameter to choose additional targets to install.

Sidenote: This is blocking my ability to use the rust-overlay to compile to WASM.

**Comment by nbp** [comment]
This would be fixed by #24.

**Comment by garbas** [comment]
I'm closing this issue since it will be fixed by #24

**Comment by nbp** [comment]
@Havvy , since #24 is now merged, can you verify if you can use the rust-overlay now?

**Comment by Havvy** [comment]
Yes. Took a bit of trial to figure out how to get different targets because I forgot what makeOverridable does, and then issues getting emscripten to work, but that was unrelated to Nix stuff, and now I can compile to WASM.

😀 😀 😀
