### ISSUE TITLE
rr fails to build when using this overlay with newer nixpkgs

### ISSUE THREAD

**Issue by ckoparkar** [mozilla/nixpkgs-mozilla#300]
As of https://github.com/NixOS/nixpkgs/commit/ad97a4885528522216877350e33f3586b838ad8e, rr in nixpkgs has switched back to accepting a `stdenv` argument instead of `gcc9Stdenv`. As a result, rr fails to build when using this overlay with newer nixpkgs:

```
error: anonymous function at /nix/store/.../pkgs/development/tools/analysis/rr/default.nix:1:1 called with unexpected argument 'gcc9Stdenv'

       at /nix/store/.../lib/customisation.nix:72:16:

           71|     let
           72|       result = f origArgs;
             |                ^
           73|
(use '--show-trace' to show detailed location information)
```

I believe this could be fixed by reverting https://github.com/mozilla/nixpkgs-mozilla/commit/66b51edb0b15aad70d2fa8ae9baae34c4eb9719e.

**Comment by Artturin** [comment]
that override should be removed https://github.com/NixOS/nixpkgs/blob/dea47fa228a4befa22bdda738f6348dd8a41e22c/pkgs/development/tools/analysis/rr/default.nix#L73

**Comment by ckoparkar** [comment]
@Artturin It looks like I created this PR too soon. I'm afraid I don't know enough Nix to follow your suggestion. Are you saying that this is something that can be / should be fixed without making changes to this overlay?

**Comment by Artturin** [comment]
rr-overlay.nix is unnecessary because `rr` already has i686-linux in its supported platforms

**Comment by ckoparkar** [comment]
Got it, thanks! 

It looks like the upstream rr package has supported i686 for quite some time (https://github.com/NixOS/nixpkgs/commit/541d30a3a932ce7aee4e7affa43089d1796b3aba).

What do you think @nbp?

**Comment by nbp** [comment]
I am ok with removing it.
