### ISSUE TITLE
parseTOML regex too large for Nix 1.12

### ISSUE THREAD

**Issue by rimmington** [mozilla/nixpkgs-mozilla#40]
After upgrading Hydra, Rust imported from the overlay failed to build with an "invalid regular expression" error in Hydra. After a lot of hunting, it turns out there's a size limit in `std::regex` (`_GLIBCXX_REGEX_STATE_LIMIT`), which the `parseTOML` regex seems to exceed. Hydra only builds with `nixUnstable`, currently Nix 1.12pre, where there [was a change in the regex type](https://github.com/NixOS/nix/commit/b05b98df7544d02387f583ca5434f33f3e9cb471) which I suspect introduced this limit.

I'm not sure what the solution is here; I gave up after a bit and [switched to importing from JSON](https://github.com/rimmington/nixpkgs-mozilla/commit/92418ae1d37868cc21a569476510b3f61811a656) instead, which works fine for our use case (pinned versions).

**Comment by nbp** [comment]
As far as I know, this cannot be solved in Nix (only) without a using a quadratic algorithm. I opened https://github.com/NixOS/nix/issues/1479 to point at one way to resolve this issue.

**Comment by nbp** [comment]
https://github.com/NixOS/nix/pull/1516 should help solve this issue by removing the hackish pattern generation and make the traversal linear with the file size. In addition this implies that we no longer need large regexp which would remove the memory errors reported by multiple users who do not have enough memory in their VMs.
