### ISSUE TITLE
Make this an overlay

### ISSUE THREAD

**Issue by nagisa** [mozilla/nixpkgs-mozilla#46]
It would be way easier to use system-wide (and per-user) if one could simply do a `nix-channel --add https://banana.peach/nixpkgs-mozilla`.

**Comment by garbas** [comment]
@nagisa It is high on our list to make this repository into [a nixpkgs overlay](http://nixos.org/nixpkgs/manual/#chap-overlays). Currently, we only provide a rust overlay, but all of nixpkgs-mozilla should be an overlay.

Providing a binaries we will just upload them to our (mozilla's) existing nix binary cache -> https://cache.mozilla-releng.net

I hope to find time to do it myself, but I can review any PR that moves us in that direction.

**Comment by nagisa** [comment]
Can overlays be used with the system-wide configuration?

**Comment by tjikini** [comment]
You can use `nixpkgs.overlays = [ (import path/to/mozilla/overlay/rust-overlay.nix) ];` in `configuration.nix`

**Comment by nbp** [comment]
For your information, I already started working on converting this repository into a proper overlay, but I am facing issues with gecko toolchains that I haven't yet got time to investigate.  I also moved the pinning mechanism to another file than default.nix, as overlays are not pinned to any specific version.

I will try to finish and push it to my repository.

**Comment by nbp** [comment]
This should be solved by #54 , which amkes the top-level `default.nix` file be a valid overlay.
Thus one can just clone nixpkgs-mozilla under ~/.config/nixpkgs/overlays/nixpkgs-mozilla and be good to go with latest nightly and latest firefox versions.
