### ISSUE TITLE
Rust overlay: cannot find bash completion files

### ISSUE THREAD

**Issue by aepsil0n** [mozilla/nixpkgs-mozilla#48]
Ran into this issue trying to use the Rust overlay on top of the NixOS unstable branch.

```rust
mv: cannot stat './etc/bash_completion.d': No such file or directory
```

So I commented out the call to `handleEtc` in the `postFixup` script. Any idea why this may not be there?

**Comment by aepsil0n** [comment]
It turns out the directory is actually called `bash_completions.d` (note the plural). I really wonder how the name changed…

**Comment by rexim** [comment]
Ran into the same problem while trying to install `pkgs.rustChannels.stable.rust (1.18.0)`. `pkgs.rustChannels.nightly.rust (1.20.0)` works perfectly.

**Comment by rexim** [comment]
After reading the comments of @aepsil0n I made the following changes https://github.com/rexim/nixpkgs-mozilla/commit/466ae2d736ad06288a9745f056253408fdbc5fe8 And now it works on stable but doesn't work on nightly. :)

Maybe we should check for both bash_compeition and bash_completions and take actions according to which one exists?

**Comment by garbas** [comment]
@rexim 👍 could you create a PR for this? eg. loop over all the folders (``"etc/bash_completion.d","share/bash_completion/completions","etc/bash_completions.d","share/bash_completions/completions";``) and then break out of the loop if ``$paths`` does not exists? eg.

```
for paths in "etc/bash_completion.d","share/bash_completion/completions","etc/bash_completions.d","share/bash_completions/completions"; do
  if [ ! -e $paths ]; then continue; fi
  ...
done
```

And maybe add a comment with a link to this issue.

**Comment by rexim** [comment]
@garbas I have a pretty limited amount of resources but I will try to do something in the nearest future. If I don't submit PR in three days, consider me not working on that. :)

**Comment by aepsil0n** [comment]
Thanks for the PR!

Interestingly, now that Rust 1.19 was released yesterday, the issue magically disappeared. I wonder, whether we should still address the issue, just in case one wants to build an old version at some point?

**Comment by garbas** [comment]
@aepsil0n I suppose it doesn't hurt if we check for 2 more folders :)
Thank you @rexim for the PR
