### ISSUE TITLE
update.nix broke with overlay conversion

### ISSUE THREAD

**Issue by seppeljordan** [mozilla/nixpkgs-mozilla#56]

**Comment by seppeljordan** [comment]
ping @nbp

**Comment by nbp** [comment]
I never used any of these scripts, can you detail the issue.
Also @garbas might know more about these update scripts.

**Comment by garbas** [comment]
@seppeljordan currently this is broken since we need to bring back pinning of the packages. I'll fix update.nix once we get all pinned files in place

**Comment by glasserc** [comment]
I think `update.nix` is working fine now. Can this be closed?
