### ISSUE TITLE
rust overlay: no such file or directory

### ISSUE THREAD

**Issue by sjmackenzie** [mozilla/nixpkgs-mozilla#66]
## Expected behaviour:
Rust nightly is downloaded and run without a problem

## Actual behaivour
Rust nightly fails with this error:
```
building path(s) ‘/nix/store/9pqiqhd52v73wmrpacv5fvhc1rys8ygy-rust-1.22.0-nightly-2017-09-11-eba374fb2’
unpacking sources
unpacking source archive /nix/store/mimkrwcq8qpch42qp9m9spj0lf3hlw52-rust-nightly-x86_64-unknown-linux-gnu.tar.gz
source root is .
setting SOURCE_DATE_EPOCH to timestamp 1505185995 of file ./env-vars
warning: file ./env-vars may be generated; SOURCE_DATE_EPOCH may be non-deterministic
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
/nix/store/r071pbl8rdb65cjlv55h67ds24pllank-stdenv/setup: ./install.sh: /bin/bash: bad interpreter: No such file or directory
builder for ‘/nix/store/kkkzdk319lq3mk8cdna2i8dylmknhbc3-rust-1.22.0-nightly-2017-09-11-eba374fb2.drv’ failed with exit code 126
```
## Steps to reproduce
install rust rightly using this repository.

**Comment by zimbatm** [comment]
Are you on NixOS?

It looks like the install.sh script needs to be patched to correct the bash path.

**Comment by sjmackenzie** [comment]
Yes I'm on NixOS.

Has an upstream path changed to break the build, I'm pretty certain it's not me.

**Comment by rushmorem** [comment]
I'm running into this issue as well. For me, on NixOS `17.09.git.b50193f`, the derivation continues to build just fine but the interpreter is not patched.

```bash
#  Cargo and other Rust binaries are available in my PATH
$ which cargo
/run/current-system/sw/bin/cargo

# But they can't be executed
$ cargo --version
bash: /run/current-system/sw/bin/cargo: No such file or directory

# Because the interpreter isn't patched
$ readelf -l $(which cargo) | grep interpreter
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
```

**Comment by zimbatm** [comment]
I don't have time to look deeply into it so here are some pointers:

There is already an attempt to patch the install script at https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix#L173, maybe the location of the script has changed?

I would also recommend submitting the change to rust-lang to always use `#!/usr/bin/env bash` for the shebang so we don't have to patch it in the first place.

**Comment by sjmackenzie** [comment]
@rushmorem try updating your `rev` to `7e54fb37cd177e6d83e4e2b7d3e3b03bd6de0e0f`. It worked for me. If it works for you I'll close the issue.

**Comment by rushmorem** [comment]
@sjmackenzie I will, thanks. Also, according to https://github.com/NixOS/nixpkgs/issues/29278#issuecomment-328888979 that should work so feel free to close.
