### ISSUE TITLE
firefox-beta-bin is out of date

### ISSUE THREAD

**Issue by sdemos** [mozilla/nixpkgs-mozilla#68]
I checked out this repo and symlinked `default.nix` to `~/.config/nixpkgs/overlays/mozilla.nix`, but when I run `nix-env -f '<nixpkgs>' -qaP | grep firefox` it says that it's current `firefox-beta-bin` version is `55.0b2` and not 57. It seems like it pulls the version from `https://product-details.mozilla.org/1.0/firefox_versions.json` but when I `curl` that it shows the correct version for `LATEST_FIREFOX_DEVEL_VERSION`. Is there something else I have to do or is this overlay out of date somehow?

**Comment by sdemos** [comment]
I guess either the overlay needs to be updated, or the readme needs to include more information, especially since there doesn't seem to be much readily available documentation on overlays in nix in the first place.

**Comment by zimbatm** [comment]
The latest builds are hidden under the "latest" prefix. I'm not sure they will appear to the package listing because we don't `recurseIntoAttrs`.

`nix-env -f '<nixpkgs>' -iA latest.firefox-nightly-bin` should do the trick
