### ISSUE TITLE
Fails to evaluate on nixUnstable

### ISSUE THREAD

**Issue by lheckemann** [mozilla/nixpkgs-mozilla#72]
```
$ nix-shell -p rustChannels.nightly.rust
error: memory limit exceeded by regular expression '([
]*(=|[[][[][a-zA-Z0-9_."*-]+[]][]]|[[][a-zA-Z0-9_."*-]+[]]|[a-zA-Z0-9_-]+|"[^"]*")[
<above line repeats ~8000 times>
]+(=|[[][[][a-zA-Z0-9_."*-]+[]][]]|[[][a-zA-Z0-9_."*-]+[]]|[a-zA-Z0-9_-]+|"[^"]*")).*', at /home/linus/projects/nixpkgs-mozilla/lib/parseTOML.nix:9:25
(use '--show-trace' to show detailed location information)
$ nix-env --version
nix-env (Nix) 1.12pre5732_fd10f6f2
```

It works fine on nix 1.11.x.

**Comment by garbas** [comment]
@nbp is this related to the different regex implementation for this 2 nix versions? Do you know of an easy way to get this to work with 1.12?

**Comment by nbp** [comment]
@lheckemann Have you updated the nixpkgs-mozilla repository? The latest contains 2 versions, one for Nix 1.11, and one for Nix 1.12.  The dispatch is based on the presence of some built-in I added my-self and the later is also more efficient.

**Comment by lheckemann** [comment]
That did the trick, thanks! Silly me…
