### ISSUE TITLE
Inconsistent reported UI version and CLI version 

### ISSUE THREAD

**Issue by coretemp** [mozilla/nixpkgs-mozilla#83]
The UI element of `~/.nix-profile/bin/firefox` shows `58.0.1 (64-bit)`, but `~/.nix-profile/bin/firefox --version` shows  `Mozilla Firefox 58.0.2`.

**Comment by garbas** [comment]
@coretemp I checked this right now and it displays the same version in either cases (`60.0a1`).

**Comment by coretemp** [comment]
@garbas How is that possible if no commit was done since Jan 25th? 

What are you running to test this? (after doing git pull in a checkout of this repository)
```
nix-env -iA nixos.latest.firefox-bin
downloading ‘https://product-details.mozilla.org/1.0/firefox_versions.json’... [0/0 KiB, 0.0 KiB/s]
replacing old ‘firefox-bin-58.0.2’
installing ‘firefox-bin-58.0.2’
downloading ‘http://download.cdn.mozilla.net/pub/firefox/releases/58.0.2/SHA512SUMS’... [0/0 KiB, 0.0 KiB/s]
downloading ‘http://download.cdn.mozilla.net/pub/firefox/releases/58.0.2/SHA512SUMS.asc’... [0/0 KiB, 0.0 KiB/s]
building path(s) ‘/nix/store/drfch4hn5j69j620ifsfk4m4wxhw4bjq-user-environment’
created 28 symlinks in user environment
```

Please write a script or a nix-expression which actually does everything to run the latest Firefox as you intend to in order to remove unclarity on NixOS.
