### ISSUE TITLE
rust-overlay: can't compile wasm

### ISSUE THREAD

**Issue by P-E-Meunier** [mozilla/nixpkgs-mozilla#92]
It seems people can compile to wasm fine on many platforms, but this overlay seems to install an outdated version of some component of the toolchain, which produces unusable wasm.

**Comment by nbp** [comment]
Have you added wasm as a `target`?
https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix#L142

**Comment by P-E-Meunier** [comment]
Yes, obviously. If you can compile the examples in wasm-bindgen, could you please share a nix expression that achieves it?

**Comment by P-E-Meunier** [comment]
Post-RustFest update: after comparing the wasm produced by a non-NixOS machine, this is likely due to a link problem.
