### ISSUE TITLE
Add Clippy as a Rust overlay extension

### ISSUE THREAD

**Issue by rushmorem** [mozilla/nixpkgs-mozilla#96]

**Comment by bkchr** [comment]
I think we should wait for clippy being a rustup extension.

**Comment by rushmorem** [comment]
It now is. See https://internals.rust-lang.org/t/clippy-is-available-as-a-rustup-component/7967.

**Comment by bkchr** [comment]
Yeah I know and you now can just add the following:
`myrust = (latest.rustChannels.nightly.rust.override { extensions = [ "clippy-preview" ];});`

And this will you install clippy.

**Comment by rushmorem** [comment]
Cool. Thanks.
